/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.util.List;

public class App {

    public static void main(String[] args) {
        List<Integer> l = 

    }
}
